name: Build

on:
  push:
  pull_request:

jobs:
  compile:
    name: Compile the stub
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build nativeJavaApplicationStub
        run: make universal

      - name: Check architectures
        run: |
          lipo -archs build/universal/nativeJavaApplicationStub | tee /dev/stderr | grep -q "x86_64 arm64"
          lipo -archs build/arm64/nativeJavaApplicationStub | grep -qx arm64
          lipo -archs build/x86_64/nativeJavaApplicationStub | grep -qx x86_64

      - name: Archive binaries
        uses: actions/upload-artifact@v5
        with:
          name: nativeJavaApplicationStub
          retention-days: 7
          path: |
            ./build/x86_64/nativeJavaApplicationStub
            ./build/arm64/nativeJavaApplicationStub
            ./build/universal/nativeJavaApplicationStub
